# Generated by Django 6.1.1 on 2026-10-03 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(max_length=200)),
                ('drug_b', models.CharField(max_length=200)),
                ('smiles_a', models.TextField(blank=True)),
                ('smiles_b', models.TextField(blank=True)),
                ('risk_level', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('major_probability', models.FloatField(default=0)),
                ('minor_probability', models.FloatField(default=0)),
                ('moderate_probability', models.FloatField(default=0)),
                ('side_effects', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
